master_build: &MasterBuild |
  node -v
  npm install -g truffle@latest
  truffle test

version: 2
jobs:
  build:
    machine:
      node:
        version: 8.9.0
    steps:
      - checkout
      - run: *MasterBuild
